<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookoPhile.DataAccess\BookoPhile.DataAccess.csproj" />
    <ProjectReference Include="..\BookoPhile.Models\BookoPhile.Models.csproj" />
    <ProjectReference Include="..\BookoPhile.Utility\BookoPhile.Utility.csproj" />
  </ItemGroup>

</Project>
